FileVersion = 1
LastConfig = "Release"
LastPlatform = "Win64"
RecentFilesList = ["src\\Session\\Tensor.bf", "src\\Session\\DenseTensor.bf", "src\\Session\\TensorUtils\\TensorBase.bf", "src\\Session\\TensorUtils\\TensorElementTypeInfo.bf", "src\\Session\\TensorUtils\\TensorTypeInfo.bf", "src\\Session\\TensorUtils\\TensorElementType.bf", "src\\Session\\Utils\\ArrayUtilities.bf", "src\\SessionOptions.bf", "src\\InferenceSession.bf", "src\\Session\\YoloClass.bf", "src\\Session\\MetaData.bf", "src\\Native\\BFloat16.bf", "src\\Native\\Enums.bf", "src\\Native\\BitOpsUtil.bf", "src\\Native\\Float16.bf", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\Object.bf", "src\\Session\\Helpers.bf", "src\\Native\\Functions.bf", "src\\Native\\Structs.bf", "Example\\src\\Program.bf"]

[MainWindow]
X = 382
Y = 68
Width = 1178
Height = 884
ShowKind = "ShowMaximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 358.0
RequestedHeight = 208.0
SizePriority = 208.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 304.0
RequestedHeight = 208.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 112.5
TabIsPinned = false
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 150.0
RequestedHeight = 150.0
SizePriority = 150.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "TensorBase.bf"
TabWidth = 117.3077
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Session\\TensorUtils\\TensorBase.bf"
CursorPos = 65
ProjectName = "OnnxRuntime"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "TensorElementTypeInfo.bf"
TabWidth = 183.6539
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Session\\TensorUtils\\TensorElementTypeInfo.bf"
CursorPos = 13
ProjectName = "OnnxRuntime"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "TensorTypeInfo.bf"
TabWidth = 139.4231
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Session\\TensorUtils\\TensorTypeInfo.bf"
CursorPos = 334
ProjectName = "OnnxRuntime"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "TensorElementType.bf"
TabWidth = 162.5
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Session\\TensorUtils\\TensorElementType.bf"
CursorPos = 344
ProjectName = "OnnxRuntime"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ArrayUtilities.bf"
TabWidth = 124.0385
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Session\\Utils\\ArrayUtilities.bf"
CursorPos = 732
VertPos = 2193.0
ProjectName = "OnnxRuntime"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "BFloat16.bf"
TabWidth = 91.53846
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Native\\BFloat16.bf"
CursorPos = 9029
ProjectName = "OnnxRuntime"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "BitOpsUtil.bf"
TabWidth = 99.23077
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Native\\BitOpsUtil.bf"
CursorPos = 13
ProjectName = "OnnxRuntime"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Float16.bf"
TabWidth = 84.80769
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Native\\Float16.bf"
CursorPos = 3328
ProjectName = "OnnxRuntime"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Tensor.bf"
TabWidth = 80.96154
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Session\\Tensor.bf"
CursorPos = 201
ProjectName = "OnnxRuntime"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "DenseTensor.bf"
TabWidth = 115.5769
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Session\\DenseTensor.bf"
CursorPos = 188
ProjectName = "OnnxRuntime"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "YoloClass.bf"
TabWidth = 97.30769
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Session\\YoloClass.bf"
CursorPos = 290
ProjectName = "OnnxRuntime"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "MetaData.bf"
TabWidth = 99.23077
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Session\\MetaData.bf"
CursorPos = 194
ProjectName = "OnnxRuntime"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Enums.bf"
TabWidth = 80.96154
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Native\\Enums.bf"
CursorPos = 194
ProjectName = "OnnxRuntime"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Structs.bf"
TabWidth = 81.92308
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Native\\Structs.bf"
CursorPos = 16999
ProjectName = "OnnxRuntime"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Functions.bf"
TabWidth = 96.34615
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Native\\Functions.bf"
CursorPos = 7230
ProjectName = "OnnxRuntime"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Helpers.bf"
TabWidth = 87.69231
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Session\\Helpers.bf"
CursorPos = 3681
ProjectName = "OnnxRuntime"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Status.bf"
TabWidth = 78.07692
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Native\\Status.bf"
CursorPos = 167
ProjectName = "OnnxRuntime"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "SessionOptions.bf"
TabWidth = 130.9615
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\SessionOptions.bf"
CursorPos = 1342
ProjectName = "OnnxRuntime"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Imports.bf"
TabWidth = 87.69231
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Native\\Imports.bf"
CursorPos = 97
ProjectName = "OnnxRuntime"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "InferenceSession.bf"
TabWidth = 137.6923
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\InferenceSession.bf"
CursorPos = 600
VertPos = 306.0
ProjectName = "OnnxRuntime"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Program.bf"
TabWidth = 93.46154
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "Example\\src\\Program.bf"
CursorPos = 129
ProjectName = "Example"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 260.0
RequestedHeight = 256.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 260.0
RequestedHeight = 260.0
SizePriority = 0.4984359
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Profile"
TabWidth = 85.57693
TabIsPinned = false
Type = "ProfilePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Errors"
TabWidth = 84.61539
TabIsPinned = false
Type = "ErrorsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 97.11539
TabIsPinned = false
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 84.61539
TabIsPinned = false
Type = "WatchPanel"
Columns = [{Width = 208.0}, {Width = 208.0}, {Width = 208.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs.Items]]
EvalStr = ""

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Auto"
TabWidth = 75.96154
TabIsPinned = false
Type = "AutoWatchPanel"
Columns = [{Width = 208.0}, {Width = 208.0}, {Width = 208.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 260.0
RequestedHeight = 260.0
SizePriority = 0.5015641
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 95.19231
TabIsPinned = false
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 102.8846
TabIsPinned = false
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 108.6538
TabIsPinned = false
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 88.46154
TabIsPinned = false
Type = "OutputPanel"

[[BookmarkFolders]]
Title = ""

[OutputFilters]
ModuleLoadMessages = false
ModuleUnloadMessages = false
ProcessExitMessages = false
ThreadCreateMessages = false
ThreadExitMessages = false
SymbolLoadMessages = false
ProgramOutput = false
