FileVersion = 1

[Project]
Name = "OnnxRuntime"
TargetType = "BeefLib"
StartupObject = "OnnxRuntime.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\onnxruntime\\onnxruntime.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/libs/onnxruntime/*.dll\")"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\onnxruntime\\onnxruntime.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/libs/onnxruntime/*.dll\")"]
OptimizationLevel = "OgPlus"
