FileVersion = 1

[Project]
Name = "OnnxRuntime"
TargetType = "BeefLib"
StartupObject = "OnnxRuntime.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\onnxruntime\\onnxruntime_providers_shared.lib", "$(ProjectDir)\\libs\\onnxruntime\\onnxruntime.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/libs/onnxruntime/*.dll\")"]
